---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-dev
  labels: 
    app: nginx
    env: dev
    team: infra

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nginx-dev-quota
  namespace: nginx-dev
spec: 
  hard: 
    requests.cpu: "400m"
    requests.memory: "400Mi"
    limits.cpu: "400m"
    limits.memory: "400Mi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dev-deployment
  namespace: nginx-dev
  labels:
    app: nginx
    env: dev
    team: infra
spec: 
  replicas: 2
  template:
    metadata:
      name: nginx-dev-app
    spec:
      containers: 
        name: nginx
        image: nginx:1.24
        ports:
          - containerPort: 80